# Generated by Django 5.2 on 2025-09-17 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0004_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
