# Generated by Django 5.2 on 2025-04-30 12:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaign", "0001_initial"),
        ("game", "0002_assetbundle_end_time_assetbundle_start_time"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprogress",
            name="scanned_locations",
        ),
        migrations.AddField(
            model_name="userprogress",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="Created At"
            ),
        ),
        migrations.AddField(
            model_name="userprogress",
            name="scanned_bundles",
            field=models.ManyToManyField(
                null=True, to="game.assetbundle", verbose_name="Scanned Bundles"
            ),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="reward_amount",
            field=models.PositiveIntegerField(default=10, verbose_name="Reward Amount"),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="reward_type",
            field=models.CharField(
                choices=[("instant", "لحظه\u200cای"), ("collective", "تجمیعی")],
                max_length=10,
                verbose_name="Reward Type",
            ),
        ),
        migrations.AlterField(
            model_name="campaignlocation",
            name="campaign",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="locations",
                to="campaign.campaign",
                verbose_name="Campaign",
            ),
        ),
        migrations.AlterField(
            model_name="campaignlocation",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="game.location",
                verbose_name="Location",
            ),
        ),
        migrations.AlterField(
            model_name="userprogress",
            name="campaign",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="campaign.campaign",
                verbose_name="Campaign",
            ),
        ),
        migrations.AlterField(
            model_name="userprogress",
            name="is_rewarded",
            field=models.BooleanField(default=False, verbose_name="Rewarded"),
        ),
        migrations.AlterField(
            model_name="userprogress",
            name="score",
            field=models.PositiveIntegerField(default=0, verbose_name="Score"),
        ),
        migrations.AlterField(
            model_name="userprogress",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
    ]
