# Generated by Django 5.2 on 2025-04-30 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("campaign", "0002_remove_userprogress_scanned_locations_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="campaign",
            options={"verbose_name": "Campaign", "verbose_name_plural": "1. Campaigns"},
        ),
        migrations.AlterModelOptions(
            name="campaignlocation",
            options={
                "verbose_name": "Campaign Location",
                "verbose_name_plural": "2. Campaign Locations",
            },
        ),
        migrations.AlterModelOptions(
            name="userprogress",
            options={
                "verbose_name": "User Progress",
                "verbose_name_plural": "3. User Progresses",
            },
        ),
    ]
