# Generated by Django 5.2 on 2025-12-16 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("campaign", "0004_weeklyevent_weeklyuserscore"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="weeklyevent",
            options={
                "verbose_name": "Weekly Event",
                "verbose_name_plural": "4. Weekly Events",
            },
        ),
        migrations.AlterModelOptions(
            name="weeklyuserscore",
            options={
                "verbose_name": "Weekly User Scores",
                "verbose_name_plural": "4. Weekly User Scores",
            },
        ),
    ]
