# Generated by Django 5.2 on 2025-12-16 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("campaign", "0005_alter_weeklyevent_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="weeklyuserscore",
            options={
                "verbose_name": "Weekly User Scores",
                "verbose_name_plural": "4.1 Weekly User Scores",
            },
        ),
    ]
