# Generated by Django 5.2 on 2025-04-23 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                ("lat", models.FloatField(verbose_name="Lat")),
                ("lng", models.FloatField(verbose_name="Long")),
                ("alt", models.FloatField(blank=True, null=True, verbose_name="alt")),
            ],
        ),
        migrations.CreateModel(
            name="AssetBundle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                ("file_url", models.URLField(verbose_name="File")),
                (
                    "locations",
                    models.ManyToManyField(
                        related_name="bundles",
                        to="game.location",
                        verbose_name="Locations",
                    ),
                ),
            ],
        ),
    ]
