# Generated by Django 5.2 on 2025-04-30 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0002_assetbundle_end_time_assetbundle_start_time"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="assetbundle",
            options={
                "verbose_name": "Asset Bundle",
                "verbose_name_plural": "2. Asset Bundles",
            },
        ),
        migrations.AlterModelOptions(
            name="location",
            options={"verbose_name": "Location", "verbose_name_plural": "1. Locations"},
        ),
    ]
