# Generated by Django 5.2 on 2025-08-20 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0003_alter_assetbundle_options_alter_location_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="assetbundle",
            name="min_score",
            field=models.PositiveIntegerField(default=10, verbose_name="Reward Amount"),
        ),
    ]
