# Generated by Django 5.2 on 2025-08-20 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0004_assetbundle_min_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="assetbundle",
            name="max_score",
            field=models.PositiveIntegerField(default=10, verbose_name="Max Score"),
        ),
        migrations.AlterField(
            model_name="assetbundle",
            name="min_score",
            field=models.PositiveIntegerField(default=10, verbose_name="Min Score"),
        ),
    ]
