# Generated by Django 5.2 on 2025-08-27 08:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0005_assetbundle_max_score_alter_assetbundle_min_score"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="assetbundle",
            options={
                "verbose_name": "Asset Bundle",
                "verbose_name_plural": "1. Asset Bundles",
            },
        ),
        migrations.AlterModelOptions(
            name="location",
            options={"verbose_name": "Location", "verbose_name_plural": "2. Locations"},
        ),
        migrations.RemoveField(
            model_name="assetbundle",
            name="max_score",
        ),
        migrations.RemoveField(
            model_name="assetbundle",
            name="min_score",
        ),
        migrations.AddField(
            model_name="assetbundle",
            name="points_per_tap",
            field=models.IntegerField(default=10, verbose_name="Points per Tap"),
        ),
        migrations.AddField(
            model_name="assetbundle",
            name="required_score_to_show",
            field=models.IntegerField(default=0, verbose_name="Required Score to show"),
        ),
        migrations.CreateModel(
            name="GameHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_start_time", models.DateTimeField(auto_now_add=True)),
                ("session_end_time", models.DateTimeField(blank=True, null=True)),
                ("score_gained", models.IntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Game History",
                "verbose_name_plural": "3. Game Histories",
            },
        ),
    ]
