# Generated by Django 5.2 on 2025-08-29 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0006_alter_assetbundle_options_alter_location_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assetbundle",
            name="locations",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="bundles",
                to="game.location",
                verbose_name="Locations",
            ),
        ),
    ]
